#/******************************************************************************
# *    Copyright (c) 2009-2012 by Hisi.
# *    All rights reserved.
# *
#******************************************************************************/

CROSS_COMPILE ?= arm-hisiv300-linux-

CPU    := hi3519
COBJS  := ddr_training.o

include ddr_training.mk

